name: r-env
channels:
  - conda-forge
dependencies:
  - r
  - r-renv=1.0.7
  - r-mass=7.3
  - r-matrix=1.6
  - r-r6=2.5
  - r-rcolorbrewer=1.1
  - r-base64enc=0.1
  - r-bslib=0.7
  - r-cachem=1.0
  - r-cli=3.6
  - r-colorspace=2.1
  - r-digest=0.6
  - r-evaluate=0.23
  - r-fansi=1.0
  - r-farver=2.1
  - r-fastmap=1.1
  - r-fontawesome=0.5
  - r-fs=1.6
  - r-ggplot2=3.5
  - r-glue=1.7
  - r-gtable=0.3
  - r-highr=0.10
  - r-htmltools=0.5
  - r-isoband=0.2
  - r-jquerylib=0.1
  - r-jsonlite=1.8
  - r-knitr=1.46
  - r-labeling=0.4
  - r-lattice=0.22
  - r-lifecycle=1.0
  - r-magrittr=2.0
  - r-memoise=2.0
  - r-mgcv=1.9
  - r-mime=0.12
  - r-munsell=0.5
  - r-nlme=3.1
  - r-pillar=1.9
  - r-pkgconfig=2.0
  - r-rappdirs=0.3
  - r-rlang=1.1
  - r-rmarkdown=2.26
  - r-sass=0.4
  - r-scales=1.3
  - r-tibble=3.2
  - r-tinytex=0.51
  - r-utf8=1.2
  - r-vctrs=0.6
  - r-viridislite=0.4
  - r-withr=3.0
  - r-xfun=0.43
  - r-yaml=2.3
