name: build

on:
  push:
    branches:
      - main
      - master

env: # Change this if needed
  Rmarkdown-file: template-computo-Rmarkdown.Rmd

jobs:
  build_computorticle:
    name: Build Computo article with Rmarkdown
    if: "contains(github.event.head_commit.message, '[build]')"
    runs-on: "macos-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Setting up miniconda with specified Python and R dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: computorbuild
          environment-file: environment.yml
          channel-priority: strict
          use-only-tar-bz2: true

      - name: Setup pandoc for Rmarkdown
        uses: r-lib/actions/setup-pandoc@v1 # setup miniconda install pandoc and pandoc-citeproc

      - name: Install additional R dependencies
        run: | 
          export LANG=en_US.UTF-8
          conda run -n computorbuild Rscript r-addons.R
          
      - name: Rendering Rmd file to HTML and PDF
        run: |          
          conda run -n computorbuild Rscript -e 'rmarkdown::render("${{ env.Rmarkdown-file }}", output_file = "index.html", output_dir = "output")'
          conda run -n computorbuild Rscript -e 'pagedown::chrome_print("output/index.html", output = "output/article.pdf")'

      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built_article
          path: output

      - name: Deploying article on gitHub pages # memo: create a branch for gh-pages first time - see below
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output

# memo ; create gh-pages first time
# git checkout --orphan gh-pages
# git reset --hard
# git commit --allow-empty -m "Initializing gh-pages branch"
# git push origin gh-pages
# git checkout main
