name: build

on:
  push:
    branches:
      - main
      - master

env: # Change this if needed
  Rmarkdown-file: template-computo-Rmarkdown.Rmd
  bin-file: environment.yml
  sys-file: system-libs
  add-file: r-addons.R

jobs:
  build_computorticle:
    name: Build Computo article with Rmarkdown
    if: "contains(github.event.head_commit.message, 'do_build')"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2
      - id: computorticle
        uses: computorg/build-Rmarkdown@v1
        with:
          Rmarkdown-file: ${{ env.Rmarkdown-file }}
          environment-file: ${{ env.bin-file }}
          systems-libs-file: ${{ env.sys-file }}
          r-addons-file: ${{ env.add-file }}
          destination: output
      - name: Deploying article on gitHub pages # memo: create a branch for gh-pages first time - see below
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output

# memo ; create gh-pages first time
# git checkout --orphan gh-pages
# git reset --hard
# git commit --allow-empty -m "Initializing gh-pages branch"
# git push origin gh-pages
# git checkout main
