name: Main Workflows

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [custom-event] 
  workflow_dispatch:

jobs:
  call_R_workflows:
    uses: ./.github/workflows/R_workflows.yml
    with:
      config-path: './config/R_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }} 
  call_quartopublish_workflows:
    uses: ./.github/workflows/quartopublish_workflows.yml
    needs: call_R_workflows
    with:
      config-path: './config/quarto_config.yml'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }} 