name: publish

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'


      - name: Download virtual environment artifact
        uses: actions/download-artifact@v3
        with:
          name: R-venv
          path: renv.zip

      - name: Decompress virtual environment
        run: |
          unzip ./renv.zip/renv.zip

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: register tinytex globally for diagram.lua
        run: |
          mkdir -p ~/.local/bin
          ~/.TinyTeX/bin/x86_64-linux/tlmgr option sys_bin ~/.local/bin
          ~/.TinyTeX/bin/x86_64-linux/tlmgr path add
          ~/.TinyTeX/bin/x86_64-linux/tlmgr install libertinus-fonts
  
      - name: Install Computo extension for Quarto
        run: |
            quarto add --no-prompt computorg/computo-quarto-extension

      - name: Configure Git
        run: |
          git config --global user.email "quentin.festor@etu.umontpellier.com"
          git config --global user.name "quarto-github-actions"

      - name: Publish with Quarto + activate environment
        env:
          QUARTO_PUBLISHER: gh-pages
        run: |
          source ./renv/bin/activate
          quarto publish template-computo-R.qmd