name: Publish

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R Dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Register TinyTeX globally for diagram.lua
        run: |
          mkdir -p ~/.local/bin
          ~/.TinyTeX/bin/x86_64-linux/tlmgr option sys_bin ~/.local/bin
          ~/.TinyTeX/bin/x86_64-linux/tlmgr path add
          ~/.TinyTeX/bin/x86_64-linux/tlmgr install libertinus-fonts
  
      - name: Install Computo extension for Quarto
        run: quarto add --no-prompt computorg/computo-quarto-extension

      - name: Configure Git
        run: |
          git config --global user.email "quentin.festor@etu.umontpellier.com"
          git config --global user.name "quarto-github-actions"

      - name: Publish with Quarto + activate environment
        env:
          QUARTO_PUBLISHER: gh-pages
        run: |
          quarto publish template-computo-R.qmd
