name: R

on:
  repository_dispatch:
    types: [custom-event]
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0 '
      - name: Install R Dependencies with renv
        uses: r-lib/actions/setup-renv@v2


      - name: create a script
        run: touch activate_env.sh

      - name: create a script with path for cache
        run: touch path_env.sh

      - name: Convert paths to JSON
        id: convert
        env:
          paths: |
            /home/runner/work/_temp/renv/
            ~/renv.lock
            /home/runner/work/template-computo-R/template-computo-R/.Rprofile
            /home/runner/.Rprofile
            /home/runner/work/_temp/Library/renv/resources/activate.R
            /home/runner/work/template-computo-R/template-computo-R/renv/activate.R
            /home/runner/work/template-computo-R/template-computo-R/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/renv/resources/activate.R
            /home/runner/work/_temp/renv/source/repository/
            /home/runner/work/_temp/renv/cache/v5/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/
            /home/runner/work/template-computo-R/template-computo-R/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/
      
        run: |
          echo "${{ env.paths }}" >> path_env.sh


      - name: Calculate SHA-256 hash and put it in the script
        id: calculate-sha256
        run: |
          touch .Rprofile
          hash=$(shasum -a 256 ".Rprofile" | awk '{ print $1 }')
          echo "sha256=${{ runner.os }}-renv-$hash" >> $GITHUB_OUTPUT

          echo "sha256=${{ runner.os }}-renv-$hash" > activate_env.sh
          echo "Rscript -e 'renv::restore()'" >> activate_env.sh

      - name: debug
        run: echo "${{ toJson(steps.calculate-sha256.outputs) }}"

      - name: Deploy an artifact
        uses: actions/upload-artifact@v3
        with: 
          name: artifact-env
          path: |
            activate_env.sh

      - name: Deploy an artifact
        uses: actions/upload-artifact@v3
        with: 
          name: artifact-cache
          path: path_env.sh


      - name: Cache environment
        uses: actions/cache/save@v4
        with:
          path: |
            /home/runner/work/_temp/renv
            ~/renv.lock
            /home/runner/work/template-computo-R/template-computo-R/.Rprofile
            /home/runner/.Rprofile
            /home/runner/work/_temp/Library/renv/resources/activate.R
            /home/runner/work/template-computo-R/template-computo-R/renv/activate.R
            /home/runner/work/template-computo-R/template-computo-R/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/renv/resources/activate.R
            /home/runner/work/_temp/renv/source/repository/
            /home/runner/work/_temp/renv/cache/v5/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/
            /home/runner/work/template-computo-R/template-computo-R/renv/library/linux-ubuntu-jammy/R-4.4/x86_64-pc-linux-gnu/
          key: ${{ steps.calculate-sha256.outputs.sha256 }}

