name: R

on:
  repository_dispatch:
    types: [custom-event]
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R Dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: lss
        run: ls /home/runner/work/_temp/renv/cache/v5

      - name: ls
        run: ls /home/runner/work/_temp/renv/index/linux-ubuntu-jammy

      - name: ls
        run: ls /home/runner/work/_temp/renv/projects
        
      - name: ls
        run: ls /home/runner/work/_temp/renv/source/repository    


      - name: create a script
        run: touch activate_env.sh

      - name: Calculate SHA-256
        id: calculate-sha256
        run: |
          echo "sha256=Ubuntu 22.04.4 LTS-R version 4.4.0 (2024-04-24)-1-b573baa189b31452f33798ff25911944e34db48a0ae0eb2e5499054ef53673d5" >> $GITHUB_OUTPUT
          
      - name: script
        run: |
          echo "sha256=Ubuntu 22.04.4 LTS-R version 4.4.0 (2024-04-24)-1-b573baa189b31452f33798ff25911944e34db48a0ae0eb2e5499054ef53673d5" > activate_env.sh
          echo 'echo "ENV_PATHS_ROOT=/home/runner/work/_temp/renv" >> \$GITHUB_ENV' >> activate_env.sh
          echo 'source("renv/activate.R")' >> activate_env.sh
          echo "renv::restore()" >> activate_env.sh
          echo "renv::activate" >> activate_env.sh


      - name: Deploy an artifact
        uses: actions/upload-artifact@v3
        with: 
          name: artifact-env
          path: activate_env.sh




