name: R

on:
  repository_dispatch:
    types: [custom-event]
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Install R Dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: lss
        run: ls /home/runner/work/_temp/renv/cache/v5

      - name: ls
        run: ls /home/runner/work/_temp/renv/index/linux-ubuntu-jammy

      - name: ls
        run: ls /home/runner/work/_temp/renv/projects
        
      - name: ls
        run: ls /home/runner/work/_temp/renv/source/repository    

      - name: ls
        run: ls -la

      - name: ls
        run: ls -l


      - name: create a script
        run: touch activate_env.sh


      - name: Calculate SHA-256 hash and put it in the script
        id: calculate-sha256
        run: |
          hash=$(shasum -a 256 "renv" | awk '{ print $1 }')
          echo "sha256=${{ runner.os }}-renv-$hash" >> $GITHUB_OUTPUT

          echo "sha256=${{ runner.os }}-renv-$hash" > activate_env.sh
          echo 'echo "ENV_PATHS_ROOT=/home/runner/work/_temp/renv" >> \$GITHUB_ENV' >> activate_env.sh
          echo "ls -la" >> activate_env.sh
          echo 'Rscript -e "renv::restore(renv.lock)"' >> activate_env.sh
          echo "ls -la" >> activate_env.sh

      - name: Deploy an artifact
        uses: actions/upload-artifact@v3
        with: 
          name: artifact-env
          path: activate_env.sh


      - name: Cache environment
        uses: actions/cache/save@v4
        with:
          path: |
            ~/renv
            ~/renv.lock
            ~/.Rprofile

          key: ${{ steps.calculate-sha256.outputs.sha256 }}

